-- ============================================
-- SEED DATA: 4 Escape Games in Tenerife
-- Languages: FR, EN, DE, ES, IT
-- ============================================

-- Use fixed UUIDs for referencing
-- Game 1: Los Cristianos - Le Code d'Ichasagua
-- Game 2: La Laguna - Le Coffre des Trois Clés
-- Game 3: Puerto de la Cruz - Le Butin de la Batería
-- Game 4: Garachico - Les Cendres de l'Âme

-- ============================================
-- GAME 1: LOS CRISTIANOS
-- ============================================
INSERT INTO games (id, title, description, cover_image, city, difficulty, estimated_duration_min, is_published, max_hints_per_step, hint_penalty_seconds)
VALUES (
  '11111111-1111-1111-1111-111111111111',
  '{"fr": "Le Code d''Ichasagua : L''Ultime Secret des Guanches", "en": "The Code of Ichasagua: The Last Secret of the Guanches", "de": "Der Code von Ichasagua: Das letzte Geheimnis der Guanchen", "es": "El Código de Ichasagua: El Último Secreto de los Guanches", "it": "Il Codice di Ichasagua: L''Ultimo Segreto dei Guanci"}'::jsonb,
  '{"fr": "En 1502, Ichasagua, le dernier roi de la résistance guanche, s''est retranché dans les montagnes du sud pour protéger un code sacré. La rumeur dit qu''il a laissé des indices cryptés dans le paysage. Votre mission : retrouver ce code avant que le soleil ne se couche derrière La Gomera.", "en": "In 1502, Ichasagua, the last king of the Guanche resistance, retreated into the southern mountains to protect a sacred code. Rumor has it he left encrypted clues in the landscape. Your mission: find this code before the sun sets behind La Gomera.", "de": "Im Jahr 1502 zog sich Ichasagua, der letzte König des Guanchen-Widerstands, in die südlichen Berge zurück, um einen heiligen Code zu schützen. Gerüchten zufolge hinterließ er verschlüsselte Hinweise in der Landschaft. Ihre Mission: Finden Sie diesen Code, bevor die Sonne hinter La Gomera untergeht.", "es": "En 1502, Ichasagua, el último rey de la resistencia guanche, se refugió en las montañas del sur para proteger un código sagrado. Se dice que dejó pistas cifradas en el paisaje. Tu misión: encontrar este código antes de que el sol se ponga tras La Gomera.", "it": "Nel 1502, Ichasagua, l''ultimo re della resistenza guancia, si rifugiò nelle montagne del sud per proteggere un codice sacro. Si dice che abbia lasciato indizi criptati nel paesaggio. La vostra missione: trovare questo codice prima che il sole tramonti dietro La Gomera."}'::jsonb,
  NULL,
  'Los Cristianos',
  4,
  210,
  TRUE,
  3,
  120
);

-- Game 1 Steps
INSERT INTO game_steps (id, game_id, step_order, title, riddle_text, answer_text, latitude, longitude, validation_radius_meters, has_photo_challenge, hints, bonus_time_seconds) VALUES

-- Step 1: Église de Los Cristianos
('11111111-0001-0001-0001-000000000001', '11111111-1111-1111-1111-111111111111', 1,
  '{"fr": "Le Sanctuaire du Vieux Village", "en": "The Old Village Sanctuary", "de": "Das Heiligtum des alten Dorfes", "es": "El Santuario del Viejo Pueblo", "it": "Il Santuario del Vecchio Villaggio"}'::jsonb,
  '{"fr": "Le nouveau temple est né des cendres de l''ancien. Rendez-vous à la Parroquia de Nuestra Señora del Carmen, le cœur spirituel des pêcheurs. Trouvez l''année de sa consécration finale sur la façade pour obtenir le premier chiffre du code.", "en": "The new temple was born from the ashes of the old one. Head to the Parroquia de Nuestra Señora del Carmen, the spiritual heart of the fishermen. Find the year of its final consecration on the facade to get the first digit of the code.", "de": "Der neue Tempel wurde aus der Asche des alten geboren. Begeben Sie sich zur Parroquia de Nuestra Señora del Carmen, dem spirituellen Herzen der Fischer. Finden Sie das Jahr der letzten Einweihung an der Fassade, um die erste Ziffer des Codes zu erhalten.", "es": "El nuevo templo nació de las cenizas del antiguo. Dirígete a la Parroquia de Nuestra Señora del Carmen, el corazón espiritual de los pescadores. Encuentra el año de su consagración final en la fachada para obtener la primera cifra del código.", "it": "Il nuovo tempio è nato dalle ceneri del vecchio. Recatevi alla Parroquia de Nuestra Señora del Carmen, il cuore spirituale dei pescatori. Trovate l''anno della sua consacrazione finale sulla facciata per ottenere la prima cifra del codice."}'::jsonb,
  '{"fr": "1990", "en": "1990", "de": "1990", "es": "1990", "it": "1990"}'::jsonb,
  28.05180, -16.71350, 40, TRUE,
  '[{"order": 1, "text": {"fr": "L''ancienne ermite a été démolie pour construire cette église.", "en": "The old hermitage was demolished to build this church.", "de": "Die alte Einsiedelei wurde abgerissen, um diese Kirche zu bauen.", "es": "La antigua ermita fue demolida para construir esta iglesia.", "it": "L''antico eremo fu demolito per costruire questa chiesa."}},
    {"order": 2, "text": {"fr": "La première pierre a été posée en 1988.", "en": "The first stone was laid in 1988.", "de": "Der erste Stein wurde 1988 gelegt.", "es": "La primera piedra se colocó en 1988.", "it": "La prima pietra fu posata nel 1988."}},
    {"order": 3, "text": {"fr": "Cherchez une date entre 1988 et 1995 sur la façade.", "en": "Look for a date between 1988 and 1995 on the facade.", "de": "Suchen Sie nach einem Datum zwischen 1988 und 1995 an der Fassade.", "es": "Busca una fecha entre 1988 y 1995 en la fachada.", "it": "Cercate una data tra il 1988 e il 1995 sulla facciata."}}]'::jsonb,
  0),

-- Step 2: Ruelles des Pionniers
('11111111-0001-0001-0001-000000000002', '11111111-1111-1111-1111-111111111111', 2,
  '{"fr": "Les Ruelles des Pionniers", "en": "The Pioneers'' Alleys", "de": "Die Gassen der Pioniere", "es": "Las Callejuelas de los Pioneros", "it": "I Vicoli dei Pionieri"}'::jsonb,
  '{"fr": "Avant les complexes de luxe, une seule famille accueillait les voyageurs. Trouvez la Calle Juan Reverón Sierra et la plaque commémorative du pionnier du tourisme qui a construit la première auberge dans les années 1920. Comptez le nombre de palmiers devant la maison historique.", "en": "Before the luxury resorts, a single family welcomed travelers. Find Calle Juan Reverón Sierra and the memorial plaque of the tourism pioneer who built the first inn in the 1920s. Count the number of palm trees in front of the historic house.", "de": "Vor den Luxusresorts empfing eine einzige Familie die Reisenden. Finden Sie die Calle Juan Reverón Sierra und die Gedenktafel des Tourismuspioniers, der in den 1920er Jahren das erste Gasthaus baute. Zählen Sie die Palmen vor dem historischen Haus.", "es": "Antes de los complejos de lujo, una sola familia acogía a los viajeros. Encuentra la Calle Juan Reverón Sierra y la placa conmemorativa del pionero del turismo que construyó la primera fonda en los años 1920. Cuenta el número de palmeras frente a la casa histórica.", "it": "Prima dei resort di lusso, una sola famiglia accoglieva i viaggiatori. Trovate la Calle Juan Reverón Sierra e la targa commemorativa del pioniere del turismo che costruì la prima locanda negli anni ''20. Contate il numero di palme davanti alla casa storica."}'::jsonb,
  '{"fr": "Famille Reverón, Fonda 1928", "en": "Reverón family, Fonda 1928", "de": "Familie Reverón, Fonda 1928", "es": "Familia Reverón, Fonda 1928", "it": "Famiglia Reverón, Fonda 1928"}'::jsonb,
  28.05136, -16.71602, 35, TRUE,
  '[{"order": 1, "text": {"fr": "La famille s''appelle Reverón.", "en": "The family name is Reverón.", "de": "Die Familie heißt Reverón.", "es": "La familia se llama Reverón.", "it": "La famiglia si chiama Reverón."}},
    {"order": 2, "text": {"fr": "Cherchez une plaque sur les murs de la rue piétonne.", "en": "Look for a plaque on the walls of the pedestrian street.", "de": "Suchen Sie nach einer Tafel an den Wänden der Fußgängerzone.", "es": "Busca una placa en las paredes de la calle peatonal.", "it": "Cercate una targa sui muri della strada pedonale."}}]'::jsonb,
  0),

-- Step 3: Port de Los Cristianos
('11111111-0001-0001-0001-000000000003', '11111111-1111-1111-1111-111111111111', 3,
  '{"fr": "Le Premier Môle du Port", "en": "The First Harbour Pier", "de": "Die erste Hafenmole", "es": "El Primer Muelle del Puerto", "it": "Il Primo Molo del Porto"}'::jsonb,
  '{"fr": "L''océan a vu naître ce port en 1523 comme simple refuge de pêcheurs. Dirigez-vous vers l''ancien quai de pierre basaltique. Trouvez la mention du premier quai de basalte pour comprendre comment Ichasagua surveillait les navires conquérants.", "en": "The ocean saw this port born in 1523 as a simple fishermen''s shelter. Head to the old basalt stone pier. Find the mention of the first basalt pier to understand how Ichasagua watched the conquerors'' ships.", "de": "Der Ozean sah die Geburt dieses Hafens im Jahr 1523 als einfacher Fischerzufluchtsort. Gehen Sie zum alten Basaltsteinkai. Finden Sie die Erwähnung des ersten Basaltkais, um zu verstehen, wie Ichasagua die Erobererschiffe beobachtete.", "es": "El océano vio nacer este puerto en 1523 como simple refugio de pescadores. Dirígete al antiguo muelle de piedra basáltica. Encuentra la mención del primer muelle de basalto para entender cómo Ichasagua vigilaba los navíos conquistadores.", "it": "L''oceano ha visto nascere questo porto nel 1523 come semplice rifugio di pescatori. Dirigetevi verso l''antico molo di pietra basaltica. Trovate il riferimento al primo molo di basalto per capire come Ichasagua sorvegliava le navi dei conquistatori."}'::jsonb,
  '{"fr": "1523 / 1934", "en": "1523 / 1934", "de": "1523 / 1934", "es": "1523 / 1934", "it": "1523 / 1934"}'::jsonb,
  28.04588, -16.71725, 50, TRUE,
  '[{"order": 1, "text": {"fr": "Le port moderne a été achevé en 1934.", "en": "The modern port was completed in 1934.", "de": "Der moderne Hafen wurde 1934 fertiggestellt.", "es": "El puerto moderno se completó en 1934.", "it": "Il porto moderno fu completato nel 1934."}},
    {"order": 2, "text": {"fr": "Cherchez une inscription sur les murs du port ou une statue liée à la mer.", "en": "Look for an inscription on the port walls or a statue related to the sea.", "de": "Suchen Sie nach einer Inschrift an den Hafenmauern oder einer Statue mit Meeresbezug.", "es": "Busca una inscripción en los muros del puerto o una estatua relacionada con el mar.", "it": "Cercate un''iscrizione sui muri del porto o una statua legata al mare."}}]'::jsonb,
  0),

-- Step 4: Montaña Guaza - Début sentier
('11111111-0001-0001-0001-000000000004', '11111111-1111-1111-1111-111111111111', 4,
  '{"fr": "L''Ascension Géologique", "en": "The Geological Ascent", "de": "Der geologische Aufstieg", "es": "La Ascensión Geológica", "it": "L''Ascensione Geologica"}'::jsonb,
  '{"fr": "Ici, la terre a coulé lentement. Montez vers la Montaña Guaza par le sentier de Los Tarajales. Touchez la roche grise et trouvez le point de vue sur La Gomera. Si vous voyez l''île voisine, vous êtes sur la terre sacrée des ancêtres. Quelle est cette roche volcanique grisâtre très visqueuse?", "en": "Here, the earth flowed slowly. Climb towards Montaña Guaza via the Los Tarajales trail. Touch the grey rock and find the viewpoint over La Gomera. If you can see the neighbouring island, you stand on the sacred land of the ancestors. What is this very viscous greyish volcanic rock?", "de": "Hier floss die Erde langsam. Steigen Sie über den Weg von Los Tarajales zur Montaña Guaza auf. Berühren Sie den grauen Felsen und finden Sie den Aussichtspunkt über La Gomera. Wenn Sie die Nachbarinsel sehen, stehen Sie auf dem heiligen Land der Vorfahren. Was ist dieses sehr zähflüssige, gräuliche Vulkangestein?", "es": "Aquí, la tierra fluyó lentamente. Sube hacia la Montaña Guaza por el sendero de Los Tarajales. Toca la roca gris y encuentra el mirador hacia La Gomera. Si ves la isla vecina, estás en la tierra sagrada de los ancestros. ¿Cuál es esta roca volcánica grisácea muy viscosa?", "it": "Qui la terra è colata lentamente. Salite verso la Montaña Guaza dal sentiero de Los Tarajales. Toccate la roccia grigia e trovate il punto panoramico su La Gomera. Se vedete l''isola vicina, siete sulla terra sacra degli antenati. Qual è questa roccia vulcanica grigiastra molto viscosa?"}'::jsonb,
  '{"fr": "Trachyte", "en": "Trachyte", "de": "Trachyt", "es": "Traquita", "it": "Trachite"}'::jsonb,
  28.04772, -16.71183, 60, TRUE,
  '[{"order": 1, "text": {"fr": "C''est une roche volcanique, pas du basalte.", "en": "It''s a volcanic rock, not basalt.", "de": "Es ist ein Vulkangestein, kein Basalt.", "es": "Es una roca volcánica, no es basalto.", "it": "È una roccia vulcanica, non basalto."}},
    {"order": 2, "text": {"fr": "Cette roche est grise et très visqueuse lors de son éruption.", "en": "This rock is grey and very viscous during eruption.", "de": "Dieses Gestein ist grau und bei Ausbrüchen sehr zähflüssig.", "es": "Esta roca es gris y muy viscosa durante la erupción.", "it": "Questa roccia è grigia e molto viscosa durante l''eruzione."}},
    {"order": 3, "text": {"fr": "Son nom commence par T-R-A...", "en": "Its name starts with T-R-A...", "de": "Sein Name beginnt mit T-R-A...", "es": "Su nombre empieza por T-R-A...", "it": "Il suo nome inizia con T-R-A..."}}]'::jsonb,
  0),

-- Step 5: Traces des Guanches
('11111111-0001-0001-0001-000000000005', '11111111-1111-1111-1111-111111111111', 5,
  '{"fr": "Les Traces des Guanches", "en": "Traces of the Guanches", "de": "Spuren der Guanchen", "es": "Las Huellas de los Guanches", "it": "Le Tracce dei Guanci"}'::jsonb,
  '{"fr": "Le plateau abrite des vestiges archéologiques réels. Cherchez les murs sans mortier — des structures circulaires en pierre sèche qui servaient d''abris aux bergers guanches. Comptez les ouvertures faisant face au sommet du Teide. Ce chiffre est la clé.", "en": "The plateau holds real archaeological remains. Look for the mortarless walls — circular dry stone structures that served as shelters for the Guanche shepherds. Count the openings facing the summit of Teide. This number is the key.", "de": "Das Plateau beherbergt echte archäologische Überreste. Suchen Sie die mörtellosen Mauern — kreisförmige Trockensteinstrukturen, die den Guanchen-Hirten als Unterschlupf dienten. Zählen Sie die Öffnungen zum Gipfel des Teide. Diese Zahl ist der Schlüssel.", "es": "La meseta alberga restos arqueológicos reales. Busca los muros sin mortero — estructuras circulares de piedra seca que servían de refugio a los pastores guanches. Cuenta las aberturas orientadas hacia la cumbre del Teide. Ese número es la clave.", "it": "L''altopiano ospita resti archeologici reali. Cercate i muri senza malta — strutture circolari in pietra a secco che servivano da rifugio ai pastori guanci. Contate le aperture rivolte verso la cima del Teide. Questo numero è la chiave."}'::jsonb,
  NULL,
  28.04100, -16.69800, 80, TRUE,
  '[{"order": 1, "text": {"fr": "Ces structures s''appellent localement des ''Goros''.", "en": "These structures are locally called ''Goros''.", "de": "Diese Strukturen werden lokal ''Goros'' genannt.", "es": "Estas estructuras se llaman localmente ''Goros''.", "it": "Queste strutture sono chiamate localmente ''Goros''."}},
    {"order": 2, "text": {"fr": "Cherchez des enclos circulaires en pierre.", "en": "Look for circular stone enclosures.", "de": "Suchen Sie kreisförmige Steinumzäunungen.", "es": "Busca recintos circulares de piedra.", "it": "Cercate recinti circolari in pietra."}}]'::jsonb,
  0),

-- Step 6: Sommet - Vértice Geodésico
('11111111-0001-0001-0001-000000000006', '11111111-1111-1111-1111-111111111111', 6,
  '{"fr": "Le Climax au Vértice Geodésico", "en": "The Climax at the Geodetic Vertex", "de": "Der Höhepunkt am geodätischen Punkt", "es": "El Clímax en el Vértice Geodésico", "it": "Il Climax al Vertice Geodetico"}'::jsonb,
  '{"fr": "Vous êtes au point où le ciel touche la terre, au sommet de la Montaña Guaza (428 m). Le code final est inscrit sur le métal scellé au sommet du pilier de béton blanc de 1,20 m. Ichasagua a préféré se donner la mort ici plutôt que de se rendre en 1502. Entrez le code pour honorer sa mémoire.", "en": "You stand where sky meets earth, at the summit of Montaña Guaza (428 m). The final code is inscribed on the metal sealed at the top of the 1.20 m white concrete pillar. Ichasagua chose death here over surrender in 1502. Enter the code to honour his memory.", "de": "Sie stehen dort, wo der Himmel die Erde berührt, auf dem Gipfel der Montaña Guaza (428 m). Der finale Code ist auf dem Metall versiegelt auf der Spitze des 1,20 m weißen Betonsäule eingraviert. Ichasagua wählte hier 1502 den Tod statt der Kapitulation. Geben Sie den Code ein, um sein Andenken zu ehren.", "es": "Estás en el punto donde el cielo toca la tierra, en la cima de la Montaña Guaza (428 m). El código final está inscrito en el metal sellado en la cima del pilar de hormigón blanco de 1,20 m. Ichasagua prefirió la muerte antes que rendirse en 1502. Introduce el código para honrar su memoria.", "it": "Siete nel punto dove il cielo tocca la terra, in cima alla Montaña Guaza (428 m). Il codice finale è inciso sul metallo sigillato in cima al pilastro di cemento bianco di 1,20 m. Ichasagua scelse la morte piuttosto che arrendersi nel 1502. Inserite il codice per onorare la sua memoria."}'::jsonb,
  '{"fr": "1502", "en": "1502", "de": "1502", "es": "1502", "it": "1502"}'::jsonb,
  28.03950, -16.69500, 30, TRUE,
  '[{"order": 1, "text": {"fr": "Cherchez le cylindre de béton blanc au sommet.", "en": "Look for the white concrete cylinder at the summit.", "de": "Suchen Sie den weißen Betonzylinder auf dem Gipfel.", "es": "Busca el cilindro de hormigón blanco en la cima.", "it": "Cercate il cilindro di cemento bianco in cima."}},
    {"order": 2, "text": {"fr": "Le code est lié à l''année de mort d''Ichasagua.", "en": "The code is linked to Ichasagua''s year of death.", "de": "Der Code hängt mit dem Todesjahr von Ichasagua zusammen.", "es": "El código está relacionado con el año de muerte de Ichasagua.", "it": "Il codice è legato all''anno di morte di Ichasagua."}}]'::jsonb,
  0);


-- ============================================
-- GAME 2: LA LAGUNA
-- ============================================
INSERT INTO games (id, title, description, cover_image, city, difficulty, estimated_duration_min, is_published, max_hints_per_step, hint_penalty_seconds)
VALUES (
  '22222222-2222-2222-2222-222222222222',
  '{"fr": "Le Coffre des Trois Clés : L''Ombre d''Amaro Pargo", "en": "The Chest of Three Keys: The Shadow of Amaro Pargo", "de": "Die Truhe der drei Schlüssel: Der Schatten von Amaro Pargo", "es": "El Cofre de las Tres Llaves: La Sombra de Amaro Pargo", "it": "Il Forziere delle Tre Chiavi: L''Ombra di Amaro Pargo"}'::jsonb,
  '{"fr": "Amaro Pargo (1678-1747), le plus célèbre corsaire des Canaries, a dissimulé une partie de sa fortune au cœur de sa ville natale, La Laguna, classée à l''UNESCO. Décodez son testament urbain pour retrouver le Trésor de l''Âme avant que la cloche de la cathédrale ne sonne le glas.", "en": "Amaro Pargo (1678-1747), the most famous corsair of the Canaries, hid part of his fortune in the heart of his native town, La Laguna, a UNESCO World Heritage site. Decode his urban testament to find the Treasure of the Soul before the cathedral bell tolls.", "de": "Amaro Pargo (1678-1747), der berühmteste Korsar der Kanaren, versteckte einen Teil seines Vermögens im Herzen seiner Geburtsstadt La Laguna, UNESCO-Welterbe. Entschlüsseln Sie sein städtisches Testament, um den Schatz der Seele zu finden, bevor die Kathedralenglocke läutet.", "es": "Amaro Pargo (1678-1747), el corsario más famoso de Canarias, escondió parte de su fortuna en el corazón de su ciudad natal, La Laguna, Patrimonio de la Humanidad. Descifra su testamento urbano para encontrar el Tesoro del Alma antes de que suene la campana de la catedral.", "it": "Amaro Pargo (1678-1747), il più famoso corsaro delle Canarie, nascose parte della sua fortuna nel cuore della sua città natale, La Laguna, patrimonio UNESCO. Decodificate il suo testamento urbano per trovare il Tesoro dell''Anima prima che la campana della cattedrale suoni."}'::jsonb,
  NULL,
  'San Cristóbal de La Laguna',
  3,
  150,
  TRUE,
  3,
  120
);

INSERT INTO game_steps (id, game_id, step_order, title, riddle_text, answer_text, latitude, longitude, validation_radius_meters, has_photo_challenge, hints, bonus_time_seconds) VALUES

-- Step 1: Plaza del Adelantado
('22222222-0001-0001-0001-000000000001', '22222222-2222-2222-2222-222222222222', 1,
  '{"fr": "Le Serment du Gouverneur", "en": "The Governor''s Oath", "de": "Der Eid des Gouverneurs", "es": "El Juramento del Gobernador", "it": "Il Giuramento del Governatore"}'::jsonb,
  '{"fr": "Le jeu commence sur la place fondatrice. Observez la Casa del Corregidor et sa façade en pierre volcanique rougeâtre. Cherchez l''écusson sculpté au-dessus de la porte principale. Comptez le nombre de tours présentes sur le blason de la cité.", "en": "The game starts at the founding square. Observe the Casa del Corregidor and its reddish volcanic stone facade. Look for the sculpted coat of arms above the main door. Count the number of towers on the city''s coat of arms.", "de": "Das Spiel beginnt am Gründungsplatz. Betrachten Sie die Casa del Corregidor und ihre rötliche Vulkansteinfassade. Suchen Sie das gemeißelte Wappen über der Haupttür. Zählen Sie die Türme auf dem Stadtwappen.", "es": "El juego comienza en la plaza fundacional. Observa la Casa del Corregidor y su fachada de piedra volcánica rojiza. Busca el escudo esculpido sobre la puerta principal. Cuenta el número de torres en el blasón de la ciudad.", "it": "Il gioco inizia nella piazza fondatrice. Osservate la Casa del Corregidor e la sua facciata in pietra vulcanica rossastra. Cercate lo stemma scolpito sopra la porta principale. Contate il numero di torri sullo stemma della città."}'::jsonb,
  NULL,
  28.48667, -16.31584, 40, TRUE,
  '[{"order": 1, "text": {"fr": "Le bâtiment date du XVIe siècle.", "en": "The building dates from the 16th century.", "de": "Das Gebäude stammt aus dem 16. Jahrhundert.", "es": "El edificio data del siglo XVI.", "it": "L''edificio risale al XVI secolo."}},
    {"order": 2, "text": {"fr": "Levez les yeux au-dessus de la porte principale.", "en": "Look up above the main door.", "de": "Schauen Sie über die Haupttür.", "es": "Mira hacia arriba sobre la puerta principal.", "it": "Guardate in alto sopra la porta principale."}}]'::jsonb,
  0),

-- Step 2: Couvent Santa Catalina
('22222222-0001-0001-0001-000000000002', '22222222-2222-2222-2222-222222222222', 2,
  '{"fr": "Le Secret de la Siervita", "en": "The Secret of the Siervita", "de": "Das Geheimnis der Siervita", "es": "El Secreto de la Siervita", "it": "Il Segreto della Siervita"}'::jsonb,
  '{"fr": "Amaro Pargo avait une dévotion immense pour la religieuse María de León, dite La Siervita. Devant les grilles du Monasterio de Santa Catalina de Siena, observez les ajimeces — ces fenêtres à jalousie en bois qui permettaient aux nonnes de voir sans être vues. Trouvez la plaque commémorative : quel est le jour du mois de février où l''on expose son corps intact au public?", "en": "Amaro Pargo had immense devotion to the nun María de León, known as La Siervita. Before the gates of the Monastery of Santa Catalina de Siena, observe the ajimeces — wooden lattice windows that allowed the nuns to see without being seen. Find the memorial plaque: what day in February is her intact body displayed to the public?", "de": "Amaro Pargo hatte eine immense Verehrung für die Nonne María de León, bekannt als La Siervita. Vor den Gittern des Klosters Santa Catalina de Siena beobachten Sie die Ajimeces — hölzerne Gitterfenster, die es den Nonnen ermöglichten zu sehen, ohne gesehen zu werden. Finden Sie die Gedenktafel: An welchem Tag im Februar wird ihr unversehrter Körper der Öffentlichkeit gezeigt?", "es": "Amaro Pargo tenía una inmensa devoción por la religiosa María de León, conocida como La Siervita. Ante las rejas del Monasterio de Santa Catalina de Siena, observa los ajimeces — ventanas de celosía de madera que permitían a las monjas ver sin ser vistas. Encuentra la placa conmemorativa: ¿qué día de febrero se expone su cuerpo intacto al público?", "it": "Amaro Pargo aveva un''immensa devozione per la religiosa María de León, detta La Siervita. Davanti alle grate del Monastero di Santa Catalina de Siena, osservate gli ajimeces — finestre a gelosia in legno che permettevano alle monache di vedere senza essere viste. Trovate la targa commemorativa: in quale giorno di febbraio il suo corpo intatto viene esposto al pubblico?"}'::jsonb,
  '{"fr": "15 février", "en": "February 15", "de": "15. Februar", "es": "15 de febrero", "it": "15 febbraio"}'::jsonb,
  28.48778, -16.31417, 35, TRUE,
  '[{"order": 1, "text": {"fr": "Trois clés ouvrent le sarcophage de la sainte.", "en": "Three keys open the saint''s sarcophagus.", "de": "Drei Schlüssel öffnen den Sarkophag der Heiligen.", "es": "Tres llaves abren el sarcófago de la santa.", "it": "Tre chiavi aprono il sarcofago della santa."}},
    {"order": 2, "text": {"fr": "La réponse est un jour au milieu du mois de février.", "en": "The answer is a day in the middle of February.", "de": "Die Antwort ist ein Tag Mitte Februar.", "es": "La respuesta es un día a mediados de febrero.", "it": "La risposta è un giorno a metà febbraio."}}]'::jsonb,
  0),

-- Step 3: Ruines San Agustín
('22222222-0001-0001-0001-000000000003', '22222222-2222-2222-2222-222222222222', 3,
  '{"fr": "Les Pierres de Sang", "en": "The Blood Stones", "de": "Die Blutsteine", "es": "Las Piedras de Sangre", "it": "Le Pietre di Sangue"}'::jsonb,
  '{"fr": "Empruntez la Calle San Agustín, la rue la plus historique. Les ruines de l''Église de San Agustín, détruite par un incendie en 1964, se dressent encore. Le feu a dévoré le toit, mais pas la foi. Comptez les arches de pierre calcinée qui font face au ciel sur le côté gauche de la nef ouverte.", "en": "Walk down Calle San Agustín, the most historic street. The ruins of the Church of San Agustín, destroyed by fire in 1964, still stand. Fire consumed the roof but not the faith. Count the charred stone arches facing the sky on the left side of the open nave.", "de": "Gehen Sie die Calle San Agustín entlang, die historischste Straße. Die Ruinen der Kirche San Agustín, 1964 durch Feuer zerstört, stehen noch. Das Feuer verzehrte das Dach, aber nicht den Glauben. Zählen Sie die verkohlten Steinbögen, die auf der linken Seite des offenen Kirchenschiffs zum Himmel zeigen.", "es": "Recorre la Calle San Agustín, la calle más histórica. Las ruinas de la Iglesia de San Agustín, destruida por un incendio en 1964, aún se mantienen en pie. El fuego devoró el techo, pero no la fe. Cuenta los arcos de piedra calcinada que miran al cielo en el lado izquierdo de la nave abierta.", "it": "Percorrete la Calle San Agustín, la via più storica. Le rovine della Chiesa di San Agustín, distrutta da un incendio nel 1964, sono ancora in piedi. Il fuoco ha divorato il tetto, ma non la fede. Contate gli archi di pietra bruciata rivolti al cielo sul lato sinistro della navata aperta."}'::jsonb,
  NULL,
  28.48690, -16.31250, 35, TRUE,
  '[{"order": 1, "text": {"fr": "L''incendie a eu lieu en 1964.", "en": "The fire occurred in 1964.", "de": "Das Feuer brach 1964 aus.", "es": "El incendio ocurrió en 1964.", "it": "L''incendio avvenne nel 1964."}},
    {"order": 2, "text": {"fr": "Regardez les arches encore debout à ciel ouvert.", "en": "Look at the arches still standing open to the sky.", "de": "Betrachten Sie die noch stehenden Bögen unter freiem Himmel.", "es": "Mira los arcos que aún se mantienen a cielo abierto.", "it": "Guardate gli archi ancora in piedi a cielo aperto."}}]'::jsonb,
  0),

-- Step 4: Iglesia de la Concepción
('22222222-0001-0001-0001-000000000004', '22222222-2222-2222-2222-222222222222', 4,
  '{"fr": "La Tour de Guet", "en": "The Watchtower", "de": "Der Wachturm", "es": "La Torre de Vigía", "it": "La Torre di Vedetta"}'::jsonb,
  '{"fr": "Depuis le clocher de l''Iglesia de la Concepción, on surveillait l''arrivée des pirates. La base de la tour est faite de blocs de basalte massif. Regardez la plaque au sol dédiée au patrimoine de l''Humanité. Quelle année est gravée pour marquer la reconnaissance de la ville par l''UNESCO?", "en": "From the bell tower of the Iglesia de la Concepción, they watched for pirates. The base of the tower is made of massive basalt blocks. Look at the ground plaque dedicated to World Heritage. What year is engraved to mark the city''s recognition by UNESCO?", "de": "Vom Glockenturm der Iglesia de la Concepción beobachtete man die Ankunft der Piraten. Die Basis des Turms besteht aus massiven Basaltblöcken. Betrachten Sie die Bodenplatte zum Welterbe. Welches Jahr ist eingraviert als Anerkennung der Stadt durch die UNESCO?", "es": "Desde el campanario de la Iglesia de la Concepción se vigilaba la llegada de los piratas. La base de la torre está hecha de bloques de basalto macizo. Mira la placa en el suelo dedicada al Patrimonio de la Humanidad. ¿Qué año está grabado para marcar el reconocimiento de la ciudad por la UNESCO?", "it": "Dal campanile della Iglesia de la Concepción si sorvegliava l''arrivo dei pirati. La base della torre è fatta di blocchi di basalto massiccio. Guardate la targa a terra dedicata al Patrimonio dell''Umanità. Quale anno è inciso per segnare il riconoscimento della città dall''UNESCO?"}'::jsonb,
  '{"fr": "1999", "en": "1999", "de": "1999", "es": "1999", "it": "1999"}'::jsonb,
  28.49043, -16.32033, 40, TRUE,
  '[{"order": 1, "text": {"fr": "La Laguna est inscrite au patrimoine mondial.", "en": "La Laguna is a World Heritage site.", "de": "La Laguna ist Weltkulturerbe.", "es": "La Laguna es Patrimonio de la Humanidad.", "it": "La Laguna è Patrimonio dell''Umanità."}},
    {"order": 2, "text": {"fr": "Cherchez une plaque au sol près de la tour.", "en": "Look for a ground plaque near the tower.", "de": "Suchen Sie eine Bodenplatte in der Nähe des Turms.", "es": "Busca una placa en el suelo cerca de la torre.", "it": "Cercate una targa a terra vicino alla torre."}}]'::jsonb,
  0),

-- Step 5: Santo Domingo de Guzmán
('22222222-0001-0001-0001-000000000005', '22222222-2222-2222-2222-222222222222', 5,
  '{"fr": "Le Repos du Corsaire", "en": "The Corsair''s Rest", "de": "Die letzte Ruhe des Korsaren", "es": "El Descanso del Corsario", "it": "Il Riposo del Corsaro"}'::jsonb,
  '{"fr": "Voici le lieu le plus pirate et le moins fréquenté. À l''Iglesia de Santo Domingo de Guzmán, la pierre tombale d''Amaro Pargo repose dans la chapelle San Vicente Ferrer. Sur sa dalle funéraire, un symbole de mort vous regarde — une calavera signifiant le passage vers l''éternité. Entrez le nombre de lettres du nom complet de sa protectrice, Sor María de Jesús, pour valider la fin de votre quête.", "en": "This is the most pirate-like and least visited spot. At the Iglesia de Santo Domingo de Guzmán, Amaro Pargo''s tombstone rests in the San Vicente Ferrer chapel. On his funerary slab, a death symbol watches you — a skull signifying the passage to eternity. Enter the number of letters in his protectress''s full name, Sor María de Jesús, to complete your quest.", "de": "Dies ist der piratenhafteste und am wenigsten besuchte Ort. In der Iglesia de Santo Domingo de Guzmán ruht Amaro Pargos Grabstein in der Kapelle San Vicente Ferrer. Auf seiner Grabplatte beobachtet Sie ein Todessymbol — ein Schädel für den Übergang zur Ewigkeit. Geben Sie die Buchstabenzahl des vollständigen Namens seiner Beschützerin, Sor María de Jesús, ein.", "es": "Este es el lugar más pirata y menos frecuentado. En la Iglesia de Santo Domingo de Guzmán, la lápida de Amaro Pargo descansa en la capilla San Vicente Ferrer. En su losa funeraria, un símbolo de muerte te observa — una calavera que significa el paso a la eternidad. Introduce el número de letras del nombre completo de su protectora, Sor María de Jesús, para completar tu búsqueda.", "it": "Questo è il luogo più da pirata e meno frequentato. Nella Iglesia de Santo Domingo de Guzmán, la lapide di Amaro Pargo riposa nella cappella San Vicente Ferrer. Sulla sua lastra funeraria, un simbolo di morte vi osserva — un teschio che indica il passaggio all''eternità. Inserite il numero di lettere del nome completo della sua protettrice, Sor María de Jesús, per completare la vostra ricerca."}'::jsonb,
  '{"fr": "15", "en": "15", "de": "15", "es": "15", "it": "15"}'::jsonb,
  28.48597, -16.31308, 35, TRUE,
  '[{"order": 1, "text": {"fr": "Sa protectrice s''appelle Sor María de Jesús.", "en": "His protectress is called Sor María de Jesús.", "de": "Seine Beschützerin heißt Sor María de Jesús.", "es": "Su protectora se llama Sor María de Jesús.", "it": "La sua protettrice si chiama Sor María de Jesús."}},
    {"order": 2, "text": {"fr": "Comptez les lettres sans les espaces.", "en": "Count the letters without spaces.", "de": "Zählen Sie die Buchstaben ohne Leerzeichen.", "es": "Cuenta las letras sin los espacios.", "it": "Contate le lettere senza gli spazi."}},
    {"order": 3, "text": {"fr": "S-o-r-M-a-r-í-a-d-e-J-e-s-ú-s = 15 lettres", "en": "S-o-r-M-a-r-í-a-d-e-J-e-s-ú-s = 15 letters", "de": "S-o-r-M-a-r-í-a-d-e-J-e-s-ú-s = 15 Buchstaben", "es": "S-o-r-M-a-r-í-a-d-e-J-e-s-ú-s = 15 letras", "it": "S-o-r-M-a-r-í-a-d-e-J-e-s-ú-s = 15 lettere"}}]'::jsonb,
  0);


-- ============================================
-- GAME 3: PUERTO DE LA CRUZ
-- ============================================
INSERT INTO games (id, title, description, cover_image, city, difficulty, estimated_duration_min, is_published, max_hints_per_step, hint_penalty_seconds)
VALUES (
  '33333333-3333-3333-3333-333333333333',
  '{"fr": "Le Butin de la Batería : Le Corsaire de la Ranilla", "en": "The Battery''s Bounty: The Corsair of La Ranilla", "de": "Die Beute der Batterie: Der Korsar von La Ranilla", "es": "El Botín de la Batería: El Corsario de la Ranilla", "it": "Il Bottino della Batteria: Il Corsaro de La Ranilla"}'::jsonb,
  '{"fr": "En 1706, l''éruption du volcan a détruit le port de Garachico et de nombreux navires se sont réfugiés à Puerto de la Cruz. Le capitaine corsaire Caraveo a dissimulé ses cartes et son or dans les fortifications. Reconstituez sa route avant que la marée ne monte.", "en": "In 1706, the volcanic eruption destroyed the port of Garachico and many ships took refuge in Puerto de la Cruz. Captain corsair Caraveo hid his maps and gold in the fortifications. Retrace his route before the tide rises.", "de": "1706 zerstörte der Vulkanausbruch den Hafen von Garachico und viele Schiffe suchten Zuflucht in Puerto de la Cruz. Korsar Kapitän Caraveo versteckte seine Karten und sein Gold in den Befestigungen. Rekonstruieren Sie seine Route, bevor die Flut steigt.", "es": "En 1706, la erupción del volcán destruyó el puerto de Garachico y muchos navíos se refugiaron en Puerto de la Cruz. El capitán corsario Caraveo ocultó sus mapas y su oro en las fortificaciones. Reconstruye su ruta antes de que suba la marea.", "it": "Nel 1706, l''eruzione del vulcano distrusse il porto di Garachico e molte navi si rifugiarono a Puerto de la Cruz. Il capitano corsaro Caraveo nascose le sue mappe e il suo oro nelle fortificazioni. Ricostruite la sua rotta prima che la marea salga."}'::jsonb,
  NULL,
  'Puerto de la Cruz',
  2,
  105,
  TRUE,
  3,
  120
);

INSERT INTO game_steps (id, game_id, step_order, title, riddle_text, answer_text, latitude, longitude, validation_radius_meters, has_photo_challenge, hints, bonus_time_seconds) VALUES

-- Step 1: Batería de Santa Bárbara
('33333333-0001-0001-0001-000000000001', '33333333-3333-3333-3333-333333333333', 1,
  '{"fr": "Le Rempart des Six Soldats", "en": "The Rampart of Six Soldiers", "de": "Die Bastion der sechs Soldaten", "es": "El Baluarte de los Seis Soldados", "it": "Il Bastione dei Sei Soldati"}'::jsonb,
  '{"fr": "Face à l''océan, les canons veillaient. À la Batería de Santa Bárbara, le fort protégeait le port des pirates. Trouvez le petit escalier de pierre qui mène à la guette. Comptez le nombre de fentes (meurtrières) dans le mur principal du fort. Ce nombre est votre première clé.", "en": "Facing the ocean, the cannons kept watch. At the Batería de Santa Bárbara, the fort protected the port from pirates. Find the small stone staircase leading to the lookout. Count the number of slits (arrow loops) in the fort''s main wall. This number is your first key.", "de": "Dem Ozean zugewandt hielten die Kanonen Wache. An der Batería de Santa Bárbara schützte das Fort den Hafen vor Piraten. Finden Sie die kleine Steintreppe zur Warte. Zählen Sie die Schießscharten in der Hauptmauer des Forts. Diese Zahl ist Ihr erster Schlüssel.", "es": "Frente al océano, los cañones vigilaban. En la Batería de Santa Bárbara, el fuerte protegía el puerto de los piratas. Encuentra la pequeña escalera de piedra que lleva a la atalaya. Cuenta el número de troneras en el muro principal del fuerte. Ese número es tu primera clave.", "it": "Di fronte all''oceano, i cannoni vegliavano. Alla Batería de Santa Bárbara, il forte proteggeva il porto dai pirati. Trovate la piccola scala di pietra che porta alla vedetta. Contate il numero di feritoie nel muro principale del forte. Questo numero è la vostra prima chiave."}'::jsonb,
  '{"fr": "6", "en": "6", "de": "6", "es": "6", "it": "6"}'::jsonb,
  28.41440, -16.54870, 40, TRUE,
  '[{"order": 1, "text": {"fr": "La caserne accueillait exactement 6 soldats.", "en": "The barracks housed exactly 6 soldiers.", "de": "Die Kaserne beherbergte genau 6 Soldaten.", "es": "El cuartel albergaba exactamente 6 soldados.", "it": "La caserma ospitava esattamente 6 soldati."}},
    {"order": 2, "text": {"fr": "Montez l''escalier pour voir les meurtrières.", "en": "Climb the stairs to see the arrow loops.", "de": "Steigen Sie die Treppe hinauf, um die Schießscharten zu sehen.", "es": "Sube la escalera para ver las troneras.", "it": "Salite le scale per vedere le feritoie."}}]'::jsonb,
  0),

-- Step 2: Casa de la Real Aduana
('33333333-0001-0001-0001-000000000002', '33333333-3333-3333-3333-333333333333', 2,
  '{"fr": "Le Registre de la Douane", "en": "The Customs Registry", "de": "Das Zollregister", "es": "El Registro de la Aduana", "it": "Il Registro della Dogana"}'::jsonb,
  '{"fr": "Juste à côté du fort, la Casa de la Real Aduana est le plus ancien bâtiment civil de la ville, construit en 1620. Ici, chaque caisse d''or était pesée. Trouvez l''année où ce bureau a ouvert ses portes. Soustrayez les deux derniers chiffres pour obtenir le cap du navire.", "en": "Right next to the fort, the Casa de la Real Aduana is the oldest civilian building in town, built in 1620. Here, every chest of gold was weighed. Find the year this office opened its doors. Subtract the last two digits to get the ship''s bearing.", "de": "Direkt neben dem Fort ist die Casa de la Real Aduana das älteste zivile Gebäude der Stadt, erbaut 1620. Hier wurde jede Goldkiste gewogen. Finden Sie das Jahr, in dem dieses Büro eröffnet wurde. Subtrahieren Sie die letzten beiden Ziffern, um den Kurs des Schiffes zu erhalten.", "es": "Justo al lado del fuerte, la Casa de la Real Aduana es el edificio civil más antiguo de la ciudad, construido en 1620. Aquí se pesaba cada caja de oro. Encuentra el año en que esta oficina abrió sus puertas. Resta los dos últimos dígitos para obtener el rumbo del navío.", "it": "Proprio accanto al forte, la Casa de la Real Aduana è l''edificio civile più antico della città, costruito nel 1620. Qui si pesava ogni cassa d''oro. Trovate l''anno di apertura di questo ufficio. Sottraete le ultime due cifre per ottenere la rotta della nave."}'::jsonb,
  '{"fr": "1620", "en": "1620", "de": "1620", "es": "1620", "it": "1620"}'::jsonb,
  28.41480, -16.54870, 30, TRUE,
  '[{"order": 1, "text": {"fr": "C''est le plus ancien bâtiment civil de Puerto de la Cruz.", "en": "It''s the oldest civilian building in Puerto de la Cruz.", "de": "Es ist das älteste zivile Gebäude in Puerto de la Cruz.", "es": "Es el edificio civil más antiguo de Puerto de la Cruz.", "it": "È l''edificio civile più antico di Puerto de la Cruz."}},
    {"order": 2, "text": {"fr": "Il a aussi servi de consulat britannique.", "en": "It also served as a British consulate.", "de": "Es diente auch als britisches Konsulat.", "es": "También sirvió como consulado británico.", "it": "Ha anche servito come consolato britannico."}}]'::jsonb,
  0),

-- Step 3: Barrio de La Ranilla
('33333333-0001-0001-0001-000000000003', '33333333-3333-3333-3333-333333333333', 3,
  '{"fr": "Le Navire Fantôme de Taoro", "en": "The Phantom Ship of Taoro", "de": "Das Geisterschiff von Taoro", "es": "El Navío Fantasma de Taoro", "it": "La Nave Fantasma di Taoro"}'::jsonb,
  '{"fr": "Entrez dans le quartier de La Ranilla, célèbre pour ses murs colorés de street art. Cherchez la barque aux rames-plumes qui vole sur le mur — le mural ''Navíos Volátiles'' par l''artiste Feofl!. Une barque de bois avec des symboles aborigènes est peinte. Quel nom portait l''ancien royaume guanche de cette vallée?", "en": "Enter the La Ranilla district, famous for its colourful street art walls. Look for the boat with feather-oars flying on the wall — the ''Navíos Volátiles'' mural by artist Feofl!. A wooden boat with aboriginal symbols is painted there. What was the name of the ancient Guanche kingdom of this valley?", "de": "Betreten Sie das Viertel La Ranilla, berühmt für seine bunten Street-Art-Wände. Suchen Sie das Boot mit Federrudern, das an der Wand fliegt — das Wandbild ''Navíos Volátiles'' von Künstler Feofl!. Ein Holzboot mit Ureinwohner-Symbolen ist gemalt. Wie hieß das alte Guanchen-Königreich dieses Tals?", "es": "Entra en el barrio de La Ranilla, famoso por sus muros coloridos de arte urbano. Busca la barca con remos-pluma que vuela en el muro — el mural ''Navíos Volátiles'' del artista Feofl!. Una barca de madera con símbolos aborígenes está pintada. ¿Qué nombre llevaba el antiguo reino guanche de este valle?", "it": "Entrate nel quartiere de La Ranilla, famoso per i suoi muri colorati di street art. Cercate la barca con remi-piuma che vola sul muro — il murale ''Navíos Volátiles'' dell''artista Feofl!. Una barca di legno con simboli aborigeni è dipinta. Quale nome portava l''antico regno guancio di questa valle?"}'::jsonb,
  '{"fr": "Taoro", "en": "Taoro", "de": "Taoro", "es": "Taoro", "it": "Taoro"}'::jsonb,
  28.41480, -16.55000, 50, TRUE,
  '[{"order": 1, "text": {"fr": "Cherchez un mot inscrit sur la coque de la barque peinte.", "en": "Look for a word written on the hull of the painted boat.", "de": "Suchen Sie ein Wort auf dem Rumpf des gemalten Bootes.", "es": "Busca una palabra escrita en el casco de la barca pintada.", "it": "Cercate una parola scritta sullo scafo della barca dipinta."}},
    {"order": 2, "text": {"fr": "Le nom commence par T et a 5 lettres.", "en": "The name starts with T and has 5 letters.", "de": "Der Name beginnt mit T und hat 5 Buchstaben.", "es": "El nombre empieza por T y tiene 5 letras.", "it": "Il nome inizia con T e ha 5 lettere."}}]'::jsonb,
  0),

-- Step 4: Ermita de San Telmo
('33333333-0001-0001-0001-000000000004', '33333333-3333-3333-3333-333333333333', 4,
  '{"fr": "Le Repos du Marin", "en": "The Sailor''s Rest", "de": "Die Ruhe des Seemanns", "es": "El Descanso del Marinero", "it": "Il Riposo del Marinaio"}'::jsonb,
  '{"fr": "Les marins venaient prier ici avant de partir en mer. L''Ermita de San Telmo est nichée sur une falaise volcanique dominant l''océan. À l''intérieur du temple ou sur les panneaux d''information, trouvez l''année où l''orgue venu de Hambourg a été acquis. Les deux chiffres du milieu indiquent la distance.", "en": "Sailors came here to pray before going to sea. The Ermita de San Telmo is nestled on a volcanic cliff overlooking the ocean. Inside the chapel or on the information panels, find the year the organ from Hamburg was acquired. The two middle digits indicate the distance.", "de": "Seeleute kamen hierher, um vor der Fahrt aufs Meer zu beten. Die Ermita de San Telmo liegt auf einer Vulkanklippe mit Blick auf den Ozean. Im Inneren der Kapelle oder auf den Informationstafeln finden Sie das Jahr, in dem die Orgel aus Hamburg erworben wurde. Die beiden mittleren Ziffern zeigen die Entfernung.", "es": "Los marineros venían aquí a rezar antes de hacerse a la mar. La Ermita de San Telmo está enclavada en un acantilado volcánico dominando el océano. Dentro del templo o en los paneles informativos, encuentra el año en que se adquirió el órgano de Hamburgo. Las dos cifras del medio indican la distancia.", "it": "I marinai venivano qui a pregare prima di prendere il mare. L''Ermita de San Telmo è incastonata su una scogliera vulcanica che domina l''oceano. All''interno della cappella o sui pannelli informativi, trovate l''anno in cui fu acquisito l''organo proveniente da Amburgo. Le due cifre centrali indicano la distanza."}'::jsonb,
  '{"fr": "1776", "en": "1776", "de": "1776", "es": "1776", "it": "1776"}'::jsonb,
  28.41756, -16.54553, 35, TRUE,
  '[{"order": 1, "text": {"fr": "L''orgue a été fabriqué en Allemagne.", "en": "The organ was made in Germany.", "de": "Die Orgel wurde in Deutschland hergestellt.", "es": "El órgano fue fabricado en Alemania.", "it": "L''organo fu fabbricato in Germania."}},
    {"order": 2, "text": {"fr": "L''année est dans la seconde moitié du XVIIIe siècle.", "en": "The year is in the second half of the 18th century.", "de": "Das Jahr liegt in der zweiten Hälfte des 18. Jahrhunderts.", "es": "El año está en la segunda mitad del siglo XVIII.", "it": "L''anno è nella seconda metà del XVIII secolo."}}]'::jsonb,
  0),

-- Step 5: Castillo de San Felipe
('33333333-0001-0001-0001-000000000005', '33333333-3333-3333-3333-333333333333', 5,
  '{"fr": "Les Boulets du Château", "en": "The Castle Cannonballs", "de": "Die Kanonenkugeln der Festung", "es": "Las Balas del Castillo", "it": "Le Palle di Cannone del Castello"}'::jsonb,
  '{"fr": "Vous êtes au bastion de basalte noir du Castillo de San Felipe. Comptez le nombre de boulets de pierre encore visibles ou les créneaux face à la Playa Jardín. Multipliez-le par l''année de consécration de la chapelle San Amaro (1591) pour déverrouiller le coffre virtuel de Caraveo.", "en": "You stand at the black basalt bastion of Castillo de San Felipe. Count the visible stone cannonballs or the battlements facing Playa Jardín. Multiply by the year the San Amaro chapel was consecrated (1591) to unlock Caraveo''s virtual chest.", "de": "Sie stehen an der schwarzen Basaltbastion des Castillo de San Felipe. Zählen Sie die sichtbaren Steinkugeln oder die Zinnen Richtung Playa Jardín. Multiplizieren Sie mit dem Einweihungsjahr der San-Amaro-Kapelle (1591), um Caraveos virtuelle Truhe zu öffnen.", "es": "Estás en el bastión de basalto negro del Castillo de San Felipe. Cuenta el número de balas de piedra visibles o las almenas frente a la Playa Jardín. Multiplica por el año de consagración de la capilla San Amaro (1591) para desbloquear el cofre virtual de Caraveo.", "it": "Siete al bastione di basalto nero del Castillo de San Felipe. Contate le palle di pietra ancora visibili o i merli di fronte alla Playa Jardín. Moltiplicate per l''anno di consacrazione della cappella San Amaro (1591) per sbloccare il forziere virtuale di Caraveo."}'::jsonb,
  '{"fr": "1591", "en": "1591", "de": "1591", "es": "1591", "it": "1591"}'::jsonb,
  28.41439, -16.55850, 40, TRUE,
  '[{"order": 1, "text": {"fr": "Le Castillo de San Felipe est en basalte noir.", "en": "Castillo de San Felipe is made of black basalt.", "de": "Das Castillo de San Felipe ist aus schwarzem Basalt.", "es": "El Castillo de San Felipe es de basalto negro.", "it": "Il Castillo de San Felipe è in basalto nero."}},
    {"order": 2, "text": {"fr": "La chapelle San Amaro est la plus ancienne construction religieuse de la ville.", "en": "The San Amaro chapel is the oldest religious building in town.", "de": "Die San-Amaro-Kapelle ist das älteste religiöse Gebäude der Stadt.", "es": "La capilla San Amaro es la construcción religiosa más antigua de la ciudad.", "it": "La cappella San Amaro è la più antica costruzione religiosa della città."}}]'::jsonb,
  0);


-- ============================================
-- GAME 4: GARACHICO
-- ============================================
INSERT INTO games (id, title, description, cover_image, city, difficulty, estimated_duration_min, is_published, max_hints_per_step, hint_penalty_seconds)
VALUES (
  '44444444-4444-4444-4444-444444444444',
  '{"fr": "Les Cendres de l''Âme : Le Secret du Banquier Génois", "en": "Ashes of the Soul: The Genoese Banker''s Secret", "de": "Asche der Seele: Das Geheimnis des genuesischen Bankiers", "es": "Las Cenizas del Alma: El Secreto del Banquero Genovés", "it": "Le Ceneri dell''Anima: Il Segreto del Banchiere Genovese"}'::jsonb,
  '{"fr": "Garachico, la Pompéi canarienne. Fondée en 1496 par le banquier génois Cristóbal de Ponte, la ville fut le port le plus important de Tenerife avant que l''éruption de 1706 ne scelle définitivement le port. Vous incarnez des descendants de la famille De Ponte qui découvrent un codex crypté menant à un trésor immatériel.", "en": "Garachico, the Canarian Pompeii. Founded in 1496 by Genoese banker Cristóbal de Ponte, the town was Tenerife''s most important port before the 1706 eruption sealed the harbour forever. You play as descendants of the De Ponte family who discover an encrypted codex leading to an immaterial treasure.", "de": "Garachico, das kanarische Pompeji. 1496 vom genuesischen Bankier Cristóbal de Ponte gegründet, war die Stadt Teneriffas wichtigster Hafen, bevor der Ausbruch von 1706 den Hafen für immer versiegelte. Sie spielen Nachkommen der Familie De Ponte, die einen verschlüsselten Codex entdecken, der zu einem immateriellen Schatz führt.", "es": "Garachico, la Pompeya canaria. Fundada en 1496 por el banquero genovés Cristóbal de Ponte, la ciudad fue el puerto más importante de Tenerife antes de que la erupción de 1706 sellara definitivamente el puerto. Encarnáis a descendientes de la familia De Ponte que descubren un códice cifrado que conduce a un tesoro inmaterial.", "it": "Garachico, la Pompei canaria. Fondata nel 1496 dal banchiere genovese Cristóbal de Ponte, la città fu il porto più importante di Tenerife prima che l''eruzione del 1706 sigillasse definitivamente il porto. Interpretate i discendenti della famiglia De Ponte che scoprono un codice criptato che conduce a un tesoro immateriale."}'::jsonb,
  NULL,
  'Garachico',
  4,
  165,
  TRUE,
  3,
  120
);

INSERT INTO game_steps (id, game_id, step_order, title, riddle_text, answer_text, latitude, longitude, validation_radius_meters, has_photo_challenge, hints, bonus_time_seconds) VALUES

-- Step 1: Castillo de San Miguel
('44444444-0001-0001-0001-000000000001', '44444444-4444-4444-4444-444444444444', 1,
  '{"fr": "La Sentinelle de Pierre", "en": "The Stone Sentinel", "de": "Der steinerne Wächter", "es": "El Centinela de Piedra", "it": "La Sentinella di Pietra"}'::jsonb,
  '{"fr": "Au Castillo de San Miguel, forteresse de roche de lave construite en 1575, cinq blasons surplombent la porte principale — un nombre inégalé aux Canaries. Ils représentent la Couronne d''Espagne, l''île de Tenerife et des familles nobles. Identifiez le nombre total de tours gravées sur ces boucliers. Depuis le toit, comparez les piscines naturelles d''El Caletón avec le passé : le volcan destructeur est devenu créateur.", "en": "At the Castillo de San Miguel, a lava rock fortress built in 1575, five coats of arms hang above the main gate — unmatched in the Canaries. They represent the Spanish Crown, the island of Tenerife, and noble families. Identify the total number of towers carved on these shields. From the roof, compare El Caletón''s natural pools with the past: the destructive volcano became a creator.", "de": "Am Castillo de San Miguel, einer 1575 erbauten Lavafestung, befinden sich fünf Wappen über dem Haupttor — einzigartig auf den Kanaren. Sie repräsentieren die spanische Krone, die Insel Teneriffa und Adelsfamilien. Identifizieren Sie die Gesamtzahl der Türme auf diesen Schildern. Vom Dach aus vergleichen Sie die Naturpools von El Caletón mit der Vergangenheit: der zerstörerische Vulkan wurde zum Schöpfer.", "es": "En el Castillo de San Miguel, fortaleza de roca de lava construida en 1575, cinco blasones dominan la puerta principal — cifra inigualada en Canarias. Representan la Corona de España, la isla de Tenerife y familias nobles. Identifica el número total de torres grabadas en estos escudos. Desde el techo, compara las piscinas naturales de El Caletón con el pasado: el volcán destructor se convirtió en creador.", "it": "Al Castillo de San Miguel, fortezza di roccia lavica costruita nel 1575, cinque stemmi sovrastano la porta principale — un numero ineguagliato alle Canarie. Rappresentano la Corona di Spagna, l''isola di Tenerife e famiglie nobili. Identificate il numero totale di torri incise su questi scudi. Dal tetto, confrontate le piscine naturali di El Caletón con il passato: il vulcano distruttore è diventato creatore."}'::jsonb,
  NULL,
  28.37320, -16.76606, 40, TRUE,
  '[{"order": 1, "text": {"fr": "Cherchez les 5 blasons au-dessus de la porte principale.", "en": "Look for the 5 coats of arms above the main gate.", "de": "Suchen Sie die 5 Wappen über dem Haupttor.", "es": "Busca los 5 blasones sobre la puerta principal.", "it": "Cercate i 5 stemmi sopra la porta principale."}},
    {"order": 2, "text": {"fr": "Le fort a survécu miraculeusement à l''éruption de 1706.", "en": "The fort miraculously survived the 1706 eruption.", "de": "Die Festung überstand die Eruption von 1706 auf wundersame Weise.", "es": "El fuerte sobrevivió milagrosamente a la erupción de 1706.", "it": "Il forte sopravvisse miracolosamente all''eruzione del 1706."}},
    {"order": 3, "text": {"fr": "Montez sur le toit pour la vue panoramique sur El Caletón.", "en": "Go up to the roof for the panoramic view of El Caletón.", "de": "Steigen Sie aufs Dach für den Panoramablick auf El Caletón.", "es": "Sube al techo para la vista panorámica de El Caletón.", "it": "Salite sul tetto per la vista panoramica su El Caletón."}}]'::jsonb,
  0),

-- Step 2: Puerta de Tierra
('44444444-0001-0001-0001-000000000002', '44444444-4444-4444-4444-444444444444', 2,
  '{"fr": "Le Sang de la Terre", "en": "The Blood of the Earth", "de": "Das Blut der Erde", "es": "La Sangre de la Tierra", "it": "Il Sangue della Terra"}'::jsonb,
  '{"fr": "Au Parque de la Puerta de Tierra, l''ancienne porte de pierre par laquelle passaient toutes les marchandises est aujourd''hui à plusieurs centaines de mètres de la côte — preuve de l''ampleur de l''éruption. Trouvez le pressoir à vin historique (lagar). Reliez-le à la statue du Motín del Vino sur l''avenue Adolfo Suárez. L''inscription sur le piédestal mentionne une nuit de 1666 où des torrents de vin coulèrent dans Garachico.", "en": "At the Parque de la Puerta de Tierra, the old stone gate through which all goods passed is now several hundred metres from the coast — proof of the eruption''s scale. Find the historic wine press (lagar). Link it to the Wine Revolt statue on Avenida Adolfo Suárez. The inscription on the pedestal mentions a night in 1666 when torrents of wine flowed through Garachico.", "de": "Im Parque de la Puerta de Tierra ist das alte Steintor, durch das alle Waren passierten, heute mehrere hundert Meter von der Küste entfernt — Beweis für das Ausmaß des Ausbruchs. Finden Sie die historische Weinpresse (Lagar). Verbinden Sie sie mit der Statue des Weinaufstands auf der Avenida Adolfo Suárez. Die Inschrift auf dem Sockel erwähnt eine Nacht 1666, als Weinströme durch Garachico flossen.", "es": "En el Parque de la Puerta de Tierra, la antigua puerta de piedra por la que pasaban todas las mercancías está hoy a varios cientos de metros de la costa — prueba de la magnitud de la erupción. Encuentra el lagar histórico. Relaciónalo con la estatua del Motín del Vino en la avenida Adolfo Suárez. La inscripción del pedestal menciona una noche de 1666 en la que torrentes de vino corrieron por Garachico.", "it": "Al Parque de la Puerta de Tierra, l''antico portale di pietra attraverso il quale passavano tutte le merci si trova oggi a diverse centinaia di metri dalla costa — prova della portata dell''eruzione. Trovate il torchio storico (lagar). Collegatelo alla statua del Motín del Vino sull''Avenida Adolfo Suárez. L''iscrizione sul piedistallo menziona una notte del 1666 in cui torrenti di vino scorsero per Garachico."}'::jsonb,
  '{"fr": "1666", "en": "1666", "de": "1666", "es": "1666", "it": "1666"}'::jsonb,
  28.37162, -16.76530, 50, TRUE,
  '[{"order": 1, "text": {"fr": "Cherchez le pressoir à vin dans le parc tropical.", "en": "Look for the wine press in the tropical park.", "de": "Suchen Sie die Weinpresse im tropischen Park.", "es": "Busca el lagar en el parque tropical.", "it": "Cercate il torchio nel parco tropicale."}},
    {"order": 2, "text": {"fr": "La révolte de 1666 était contre le monopole anglais du vin.", "en": "The 1666 revolt was against the English wine monopoly.", "de": "Der Aufstand von 1666 richtete sich gegen das englische Weinmonopol.", "es": "La revuelta de 1666 fue contra el monopolio inglés del vino.", "it": "La rivolta del 1666 fu contro il monopolio inglese del vino."}}]'::jsonb,
  0),

-- Step 3: Plaza de la Libertad
('44444444-0001-0001-0001-000000000003', '44444444-4444-4444-4444-444444444444', 3,
  '{"fr": "Le Cœur de la Résilience", "en": "The Heart of Resilience", "de": "Das Herz der Widerstandskraft", "es": "El Corazón de la Resiliencia", "it": "Il Cuore della Resilienza"}'::jsonb,
  '{"fr": "La Plaza de la Libertad est l''épicentre de toutes les reconstructions. Trouvez le monument de Simón Bolívar — dont les ancêtres étaient originaires de Garachico. Cherchez la corrélation entre les étoiles du monument et les fenêtres de la Casa de Piedra, palais des comtes de La Gomera. Sa façade est un chef-d''œuvre taillé par des maîtres de Grande Canarie.", "en": "The Plaza de la Libertad is the epicentre of all reconstructions. Find the Simón Bolívar monument — whose ancestors came from Garachico. Look for the correlation between the stars on the monument and the windows of the Casa de Piedra, palace of the Counts of La Gomera. Its facade is a masterpiece carved by masters from Gran Canaria.", "de": "Die Plaza de la Libertad ist das Epizentrum aller Rekonstruktionen. Finden Sie das Simón-Bolívar-Denkmal — dessen Vorfahren aus Garachico stammten. Suchen Sie die Verbindung zwischen den Sternen des Denkmals und den Fenstern der Casa de Piedra, dem Palast der Grafen von La Gomera. Die Fassade ist ein Meisterwerk, von Meistern aus Gran Canaria geschaffen.", "es": "La Plaza de la Libertad es el epicentro de todas las reconstrucciones. Encuentra el monumento a Simón Bolívar — cuyos ancestros eran originarios de Garachico. Busca la correlación entre las estrellas del monumento y las ventanas de la Casa de Piedra, palacio de los condes de La Gomera. Su fachada es una obra maestra tallada por maestros de Gran Canaria.", "it": "La Plaza de la Libertad è l''epicentro di tutte le ricostruzioni. Trovate il monumento a Simón Bolívar — i cui antenati erano originari di Garachico. Cercate la correlazione tra le stelle del monumento e le finestre della Casa de Piedra, palazzo dei conti de La Gomera. La sua facciata è un capolavoro scolpito da maestri di Gran Canaria."}'::jsonb,
  NULL,
  28.37318, -16.76461, 40, TRUE,
  '[{"order": 1, "text": {"fr": "Les ancêtres de Bolívar venaient de Garachico.", "en": "Bolívar''s ancestors came from Garachico.", "de": "Bolívars Vorfahren kamen aus Garachico.", "es": "Los ancestros de Bolívar eran de Garachico.", "it": "Gli antenati di Bolívar venivano da Garachico."}},
    {"order": 2, "text": {"fr": "La Casa de Piedra a survécu à la lave de 1706.", "en": "The Casa de Piedra survived the 1706 lava.", "de": "Die Casa de Piedra überlebte die Lava von 1706.", "es": "La Casa de Piedra sobrevivió a la lava de 1706.", "it": "La Casa de Piedra sopravvisse alla lava del 1706."}},
    {"order": 3, "text": {"fr": "Comparez les étoiles sur le monument aux fenêtres du palais.", "en": "Compare the stars on the monument to the palace windows.", "de": "Vergleichen Sie die Sterne am Denkmal mit den Palastfenstern.", "es": "Compara las estrellas del monumento con las ventanas del palacio.", "it": "Confrontate le stelle del monumento con le finestre del palazzo."}}]'::jsonb,
  0),

-- Step 4: Iglesia Santa Ana + Tensei Tenmoku
('44444444-0001-0001-0001-000000000004', '44444444-4444-4444-4444-444444444444', 4,
  '{"fr": "Le Phare Spirituel", "en": "The Spiritual Lighthouse", "de": "Der spirituelle Leuchtturm", "es": "El Faro Espiritual", "it": "Il Faro Spirituale"}'::jsonb,
  '{"fr": "L''Iglesia de Santa Ana, fondée en 1520 et reconstruite entre 1714 et 1721, domine la ville avec son clocher blanc Renaissance. Comptez les cloches en bronze dans les baies du beffroi. Puis rendez-vous sur le front de mer pour localiser la sculpture ''Tensei Tenmoku'' (La Porte sans porte) de l''artiste japonais Kan Yasuda. Alignez votre regard à travers cette porte de marbre vers le clocher pour découvrir l''angle révélateur. La devise de Garachico est votre réponse finale : Gloriosa en su adversidad.", "en": "The Iglesia de Santa Ana, founded in 1520 and rebuilt between 1714 and 1721, dominates the town with its white Renaissance bell tower. Count the bronze bells in the belfry bays. Then head to the waterfront to locate the ''Tensei Tenmoku'' sculpture (The Gate without a Gate) by Japanese artist Kan Yasuda. Align your gaze through this marble gate towards the bell tower to discover the revealing angle. Garachico''s motto is your final answer: Gloriosa en su adversidad.", "de": "Die 1520 gegründete und zwischen 1714 und 1721 wiederaufgebaute Iglesia de Santa Ana dominiert die Stadt mit ihrem weißen Renaissance-Glockenturm. Zählen Sie die Bronzeglocken in den Öffnungen des Glockenturms. Dann gehen Sie zum Meer, um die Skulptur ''Tensei Tenmoku'' (Das Tor ohne Tor) des japanischen Künstlers Kan Yasuda zu finden. Richten Sie Ihren Blick durch dieses Marmortor auf den Glockenturm. Garachicos Motto ist Ihre letzte Antwort: Gloriosa en su adversidad.", "es": "La Iglesia de Santa Ana, fundada en 1520 y reconstruida entre 1714 y 1721, domina la ciudad con su campanario blanco renacentista. Cuenta las campanas de bronce en los vanos del campanario. Luego dirígete al paseo marítimo para localizar la escultura ''Tensei Tenmoku'' (La Puerta sin puerta) del artista japonés Kan Yasuda. Alinea tu mirada a través de esta puerta de mármol hacia el campanario para descubrir el ángulo revelador. El lema de Garachico es tu respuesta final: Gloriosa en su adversidad.", "it": "La Iglesia de Santa Ana, fondata nel 1520 e ricostruita tra il 1714 e il 1721, domina la città con il suo campanile bianco rinascimentale. Contate le campane di bronzo nelle arcate del campanile. Poi dirigetevi sul lungomare per localizzare la scultura ''Tensei Tenmoku'' (La Porta senza porta) dell''artista giapponese Kan Yasuda. Allineate lo sguardo attraverso questa porta di marmo verso il campanile per scoprire l''angolo rivelatore. Il motto di Garachico è la vostra risposta finale: Gloriosa en su adversidad."}'::jsonb,
  '{"fr": "Gloriosa en su adversidad", "en": "Gloriosa en su adversidad", "de": "Gloriosa en su adversidad", "es": "Gloriosa en su adversidad", "it": "Gloriosa en su adversidad"}'::jsonb,
  28.37280, -16.76720, 45, TRUE,
  '[{"order": 1, "text": {"fr": "La sculpture Tensei Tenmoku est sur le front de mer.", "en": "The Tensei Tenmoku sculpture is on the waterfront.", "de": "Die Skulptur Tensei Tenmoku ist an der Küste.", "es": "La escultura Tensei Tenmoku está en el paseo marítimo.", "it": "La scultura Tensei Tenmoku è sul lungomare."}},
    {"order": 2, "text": {"fr": "Regardez à travers la porte de marbre vers l''église.", "en": "Look through the marble gate towards the church.", "de": "Schauen Sie durch das Marmortor zur Kirche.", "es": "Mira a través de la puerta de mármol hacia la iglesia.", "it": "Guardate attraverso la porta di marmo verso la chiesa."}},
    {"order": 3, "text": {"fr": "La devise est en espagnol et signifie ''Glorieuse dans son adversité''.", "en": "The motto is in Spanish and means ''Glorious in its adversity''.", "de": "Das Motto ist auf Spanisch und bedeutet ''Ruhmreich in ihrer Widrigheit''.", "es": "El lema significa ''Gloriosa en su adversidad''.", "it": "Il motto è in spagnolo e significa ''Gloriosa nella sua avversità''."}}]'::jsonb,
  0);


-- ============================================
-- DEMO ACTIVATION CODES (10 per game)
-- ============================================
INSERT INTO activation_codes (code, game_id, is_single_use, max_uses) VALUES
-- Los Cristianos
('GUAN-ICHE-2024', '11111111-1111-1111-1111-111111111111', FALSE, 100),
('DEMO-LCRI-0001', '11111111-1111-1111-1111-111111111111', TRUE, 1),
('DEMO-LCRI-0002', '11111111-1111-1111-1111-111111111111', TRUE, 1),
('DEMO-LCRI-0003', '11111111-1111-1111-1111-111111111111', TRUE, 1),
('DEMO-LCRI-0004', '11111111-1111-1111-1111-111111111111', TRUE, 1),
-- La Laguna
('AMAR-PARG-2024', '22222222-2222-2222-2222-222222222222', FALSE, 100),
('DEMO-LLAG-0001', '22222222-2222-2222-2222-222222222222', TRUE, 1),
('DEMO-LLAG-0002', '22222222-2222-2222-2222-222222222222', TRUE, 1),
('DEMO-LLAG-0003', '22222222-2222-2222-2222-222222222222', TRUE, 1),
('DEMO-LLAG-0004', '22222222-2222-2222-2222-222222222222', TRUE, 1),
-- Puerto de la Cruz
('CORS-AIRE-2024', '33333333-3333-3333-3333-333333333333', FALSE, 100),
('DEMO-PDLC-0001', '33333333-3333-3333-3333-333333333333', TRUE, 1),
('DEMO-PDLC-0002', '33333333-3333-3333-3333-333333333333', TRUE, 1),
('DEMO-PDLC-0003', '33333333-3333-3333-3333-333333333333', TRUE, 1),
('DEMO-PDLC-0004', '33333333-3333-3333-3333-333333333333', TRUE, 1),
-- Garachico
('GARA-LAVE-2024', '44444444-4444-4444-4444-444444444444', FALSE, 100),
('DEMO-GARA-0001', '44444444-4444-4444-4444-444444444444', TRUE, 1),
('DEMO-GARA-0002', '44444444-4444-4444-4444-444444444444', TRUE, 1),
('DEMO-GARA-0003', '44444444-4444-4444-4444-444444444444', TRUE, 1),
('DEMO-GARA-0004', '44444444-4444-4444-4444-444444444444', TRUE, 1);
