-- ============================================
-- Add structured "route_attractions" field to game_steps
-- ============================================
-- Until now the touristic context (a 16th-century house, a hidden
-- statue, a heritage fountain) was woven INTO the riddle prose. That
-- worked but couldn't be displayed as a separate UI element, mapped
-- on the route, or used independently of the riddle text.
--
-- New structured field: an array of points-of-interest the player
-- will physically pass on the way to this step. Each entry is a
-- short {name, fact} object so the UI can render a small
-- expandable card "Sur le chemin, ne manque pas..." above the riddle.
--
-- Shape (JSONB):
--   [
--     { "name": "Maison Borghi (XVIIe)",
--       "fact": "Balcons en fer forge classes monuments historiques" },
--     ...
--   ]
--
-- Always populated by the generation pipeline. Defaults to []
-- for legacy rows so older games keep working without backfill.

ALTER TABLE game_steps
  ADD COLUMN IF NOT EXISTS route_attractions JSONB DEFAULT '[]'::jsonb;

COMMENT ON COLUMN game_steps.route_attractions IS
  'JSONB array of {name, fact} touristic POIs along the route to this step. Generated by Claude.';
