-- 043_final_riddle_hints.sql
-- 2026-05-31 — Anti-blocage méta-finale
--
-- Contexte : 3 jeux récents (Versailles, Montoire, Bayeux) avaient des
-- méta-finales incohérentes ou triviales (1770 dans 7 vertus Latin,
-- réponse "3" mystérieuse, "FIVE" trivial). Le joueur restait soit
-- bloqué soit déçu.
--
-- Solution : narrate.ts (V5) génère désormais 3 hints progressifs pour
-- la méta-finale. Cette migration ajoute la colonne JSONB pour les
-- stocker. Le player API peut révéler les hints entre les 2 tentatives.
--
-- Structure attendue :
--   [
--     "Hint 1 LIGHT — catégorie + 1ère lettre",
--     "Hint 2 MEDIUM — 3 premières lettres + contexte thématique",
--     "Hint 3 STRONG — réponse avec 1 lettre cachée"
--   ]

ALTER TABLE public.games
  ADD COLUMN IF NOT EXISTS final_riddle_hints JSONB;

COMMENT ON COLUMN public.games.final_riddle_hints IS
  '3 progressive hints for the meta-finale riddle, generated by narrate.ts V5+. JSONB array of strings. NULL for legacy V4 games.';
